
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/team02-s23-6pm-1
owner: ucsb-cs156-s23
repo_name: team02-s23-6pm-1
pull_requests: [{"author":{"id":"U_kgDOBX6DSQ","is_bot":false,"login":"mfletcher2","name":"Max Fletcher"},"headRefName":"max-bikedelete","number":66,"title":"mf: Add DELETE endpoint for Bikes","url":"https://github.com/ucsb-cs156-s23/team02-s23-6pm-1/pull/66"},{"author":{"id":"U_kgDOBXzGpA","is_bot":false,"login":"albertyu03","name":"Albert Yu"},"headRefName":"Albert-BookDel","number":65,"title":"ay - adding delete endpoint to Book table","url":"https://github.com/ucsb-cs156-s23/team02-s23-6pm-1/pull/65"}]
